### PR TITLE
Added babel-preset-stage-0 to fix errors.

### PR DESCRIPTION
**Pull request by n8mellis**

### CODE REVIEW

**Comment by n8mellis** [comment]
I think we might want to have a larger discussion about whether or not we want to use "stage-0" syntax, which is likely to change significantly.  Thoughts?

**Comment by mstanaland** [comment]
_Hi, my name is Michael and I'm a stage 0 offender._ 

In principle I'd say we shouldn't be using any stage 0 features. Or stage 1 or 2, for that matter.

But when it comes to stage 3, I'm more torn. Using something that isn't officially in the spec seems like not the best idea for production code that has to be maintained, which I think is the goal here. On the other hand, object rest spread transforms are freakin' awesome. And Object.assign is less awesome.

So maybe a better philosophical question is how do we feel about using stage 3 features in production code? I'm not sure there's enough history to speak to the likelihood that a candidate would or would not make it into spec (stage 4), but it seems like a relatively safe bet. But a gamble nonetheless.

Moving away from theory to practice, I used a stage 3 feature in the Tables components to separate expected props (like children) from any number of additional, undetermined props. For example, when manually building a table, you could add a className, an inline style and a tabindex to a `<TableCell>` and those would merrily appear in the html as a `class="special" style="{background: yellow}" tabindex="0"`. The component doesn't know or care about those props ... it just takes what you give it and passes it through. That certainly doesn't have to be a feature, and removing it would remove the stage 3 requirement.

Are there any other components that use stage 0-3 features? Is there any thought about how we're going to write reducers (with Object.assign? With object rest spread transforms? With Immutable.js?)

**Comment by n8mellis** [comment]
To be clear, I'm not suggesting that we abandon all unofficial stuff.  I too am a big fan of the spread operator.  My specific question is whether we should be using anything that requires the `stage-0` babel plugin.  That plugin encompasses all the things that are the most likely to change.

I think so far the only thing that requires it is using static properties inside the class definition.  We can easily get away with defining them outside.  For example:

```
export class Component extends React.Component {
  static propTypes = { ... }
}
```

vs

```
export class Component extends React.Component {
  ...
}
Component.propTypes = { ... }
```

**Comment by mstanaland** [comment]
Yes - I agree and that’s a super easy change. I discovered that and thought ‘oh gee, that’s way more tidy and easier to read’ without realizing it wasn’t a close-to-being-released feature.

**Pull request merged**
