### PR TITLE
Updated webpack script to fix npm install error

### PR DESCRIPTION
**Pull request by vadnguyen**

### CODE REVIEW

**Comment by burgwyn** [comment]
`npm WARN using --force I sure hope you know what you are doing.`

**Comment by vadnguyen** [comment]
Hah, I am not sure...npm install kept failing at
`rimraf dist/ && npm run -f webpack && gulp build`

**Comment by mstanaland** [comment]
Or just (temporarily) remove the jsdocs requirement from the eslintrc ... that's what I did

Sent from my iPhone

On Feb 23, 2017, at 12:57 PM, Virginia Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hah, I am not sure...npm install kept failing at
`"build": "rimraf dist/ && npm run -f webpack && gulp build",'

**Comment by vadnguyen** [comment]
Yes, removing the require-jsdocs allows npm install to run successfully, but I had installed jsdocs when I thought I was missing the package....

**Comment by vadnguyen** [comment]
reverting this, needs further investigation.

**Pull request closed without merging**
